apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1  # İhtiyaca göre değiştirilebilir
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: md3954/nodejs:latest  # Docker Compose'daki image ile aynı olmalıdır
          ports:
            - containerPort: 4000  # Node.js uygulamanızın çalıştığı port
          env:
            - name: MYSQL_HOST  # MySQL bağlantı bilgilerini burada tanımlayabilirsiniz
              value: "mysql"       # Docker Compose'daki servis adını buraya yazmalısınız
          # Diğer ayarlar buraya eklenebilir
