version: '3.8'
services:
 app:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Admin123!
      - MYSQL_DATABASE=test

 db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Admin123!
      - MYSQL_DATABASE=test

volumes:
 mysql-data: