apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 4000  # Node.js uygulamanızın dış dünyadan erişilebileceği port
      targetPort: 4000  # Node.js uygulamanızın çalıştığı port
  type: LoadBalancer  # Node.js uygulamanıza dış dünyadan erişim sağlar
